name: 'bank_marketing_dm'
version: '1.0.0'
config-version: 2

# Configuración para dbt Cloud
profile: 'bank_marketing_dm'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuración de modelos optimizada para dbt Cloud
models:
  bank_marketing_dm:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: table
      +schema: intermediate
    marts:
      +materialized: table
      +schema: marts
      marketing:
        +materialized: table
        +schema: marketing

# Variables específicas para dbt Cloud
vars:
  # Configuración de BigQuery - se configurará en dbt Cloud
  project_id: "{{ env_var('DBT_CLOUD_PROJECT_ID') }}"
  dataset_raw: "raw"
  dataset_staging: "staging"
  dataset_intermediate: "intermediate"
  dataset_marts: "marts"
  
  # Configuración de Dataplex (opcional)
  dataplex_project: "{{ env_var('DBT_CLOUD_PROJECT_ID') }}"
  dataplex_location: "us-central1"
  dataplex_lake: "bank-marketing-lake"

# Configuración de seeds para cargar datos
seeds:
  bank_marketing_dm:
    bank_marketing:
      +schema: raw
      +column_types:
        age: int
        job: string
        marital: string
        education: string
        default: string
        balance: int
        housing: string
        loan: string
        contact: string
        day: int
        month: string
        duration: int
        campaign: int
        pdays: int
        previous: int
        poutcome: string
        y: string
    
    bank_additional:
      +schema: raw
      +column_types:
        age: int
        job: string
        marital: string
        education: string
        default: string
        balance: int
        housing: string
        loan: string
        contact: string
        day: int
        month: string
        duration: int
        campaign: int
        pdays: int
        previous: int
        poutcome: string
        emp_var_rate: float
        cons_price_idx: float
        cons_conf_idx: float
        euribor3m: float
        nr_employed: float
        y: string
