name: 'bank_marketing_dm'
version: '1.0.0'
config-version: 2

# Configuración para dbt Cloud
profile: 'bank_marketing_dm'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuración de modelos optimizada para dbt Cloud
models:
  bank_marketing_dm:
    staging:
      +materialized: view
      +schema: "dusa_prj_sandbox_staging"
    intermediate:
      +materialized: table
      +schema: "dusa_prj_sandbox_intermediate"
    marts:
      +materialized: table
      +schema: "dusa_prj_sandbox_marts"
      marketing:
        +materialized: table
        +schema: "dusa_prj_sandbox_marts_marketing"

# Variables específicas para dbt Cloud
vars:
  # Configuración de BigQuery
  project_id: "dusa-prj-sandbox"
  dataset_raw: "raw"
  dataset_staging: "dusa_prj_sandbox_staging"
  dataset_intermediate: "dusa_prj_sandbox_intermediate"
  dataset_marts: "dusa_prj_sandbox_marts"
  
  # Configuración de Dataplex (opcional)
  dataplex_project: "dusa-prj-sandbox"
  dataplex_location: "US"
  dataplex_lake: "bank-marketing-lake"