version: 2

seeds:
  - name: bank_marketing
    description: "Dataset principal de marketing bancario con información de clientes y campañas"
    config:
      column_types:
        age: int
        job: string
        marital: string
        education: string
        default: string
        balance: int
        housing: string
        loan: string
        contact: string
        day: int
        month: string
        duration: int
        campaign: int
        pdays: int
        previous: int
        poutcome: string
        y: string
    columns:
      - name: age
        description: "Edad del cliente"
        tests:
          - not_null
          - accepted_values:
              values: [17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95]
      
      - name: job
        description: "Tipo de trabajo del cliente"
        tests:
          - not_null
          - accepted_values:
              values: ['admin.', 'blue-collar', 'entrepreneur', 'housemaid', 'management', 'retired', 'self-employed', 'services', 'student', 'technician', 'unemployed', 'unknown']
      
      - name: marital
        description: "Estado civil del cliente"
        tests:
          - not_null
          - accepted_values:
              values: ['divorced', 'married', 'single', 'unknown']
      
      - name: education
        description: "Nivel educativo del cliente"
        tests:
          - not_null
          - accepted_values:
              values: ['basic.4y', 'basic.6y', 'basic.9y', 'high.school', 'illiterate', 'professional.course', 'university.degree', 'unknown']
      
      - name: default
        description: "¿Tiene crédito en mora?"
        tests:
          - not_null
          - accepted_values:
              values: ['no', 'yes', 'unknown']
      
      - name: balance
        description: "Balance promedio anual en euros"
        tests:
          - not_null
      
      - name: housing
        description: "¿Tiene préstamo hipotecario?"
        tests:
          - not_null
          - accepted_values:
              values: ['no', 'yes', 'unknown']
      
      - name: loan
        description: "¿Tiene préstamo personal?"
        tests:
          - not_null
          - accepted_values:
              values: ['no', 'yes', 'unknown']
      
      - name: contact
        description: "Tipo de comunicación de contacto"
        tests:
          - not_null
          - accepted_values:
              values: ['cellular', 'telephone']
      
      - name: day
        description: "Día del mes del último contacto"
        tests:
          - not_null
          - accepted_values:
              values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
      
      - name: month
        description: "Mes del último contacto"
        tests:
          - not_null
          - accepted_values:
              values: ['jan', 'feb', 'mar', 'apr', 'may', 'jun', 'jul', 'aug', 'sep', 'oct', 'nov', 'dec']
      
      - name: duration
        description: "Duración del último contacto en segundos"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "duration > 0"
      
      - name: campaign
        description: "Número de contactos realizados durante esta campaña"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "campaign >= 1"
      
      - name: pdays
        description: "Número de días que pasaron después de que el cliente fue contactado desde una campaña anterior"
        tests:
          - not_null
      
      - name: previous
        description: "Número de contactos realizados antes de esta campaña"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "previous >= 0"
      
      - name: poutcome
        description: "Resultado de la campaña de marketing anterior"
        tests:
          - not_null
          - accepted_values:
              values: ['failure', 'nonexistent', 'success']
      
      - name: y
        description: "¿El cliente suscribió un depósito a plazo?"
        tests:
          - not_null
          - accepted_values:
              values: ['no', 'yes']

  - name: bank_additional
    description: "Dataset adicional con información socioeconómica"
    config:
      column_types:
        age: int
        job: string
        marital: string
        education: string
        default: string
        balance: int
        housing: string
        loan: string
        contact: string
        day: int
        month: string
        duration: int
        campaign: int
        pdays: int
        previous: int
        poutcome: string
        emp_var_rate: float
        cons_price_idx: float
        cons_conf_idx: float
        euribor3m: float
        nr_employed: float
        y: string
    columns:
      - name: age
        description: "Edad del cliente"
        tests:
          - not_null
      
      - name: job
        description: "Tipo de trabajo del cliente"
        tests:
          - not_null
      
      - name: marital
        description: "Estado civil del cliente"
        tests:
          - not_null
      
      - name: education
        description: "Nivel educativo del cliente"
        tests:
          - not_null
      
      - name: default
        description: "¿Tiene crédito en mora?"
        tests:
          - not_null
      
      - name: balance
        description: "Balance promedio anual en euros"
        tests:
          - not_null
      
      - name: housing
        description: "¿Tiene préstamo hipotecario?"
        tests:
          - not_null
      
      - name: loan
        description: "¿Tiene préstamo personal?"
        tests:
          - not_null
      
      - name: contact
        description: "Tipo de comunicación de contacto"
        tests:
          - not_null
      
      - name: day
        description: "Día del mes del último contacto"
        tests:
          - not_null
      
      - name: month
        description: "Mes del último contacto"
        tests:
          - not_null
      
      - name: duration
        description: "Duración del último contacto en segundos"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "duration > 0"
      
      - name: campaign
        description: "Número de contactos realizados durante esta campaña"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "campaign >= 1"
      
      - name: pdays
        description: "Número de días que pasaron después de que el cliente fue contactado desde una campaña anterior"
        tests:
          - not_null
      
      - name: previous
        description: "Número de contactos realizados antes de esta campaña"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: "previous >= 0"
      
      - name: poutcome
        description: "Resultado de la campaña de marketing anterior"
        tests:
          - not_null
      
      - name: emp_var_rate
        description: "Tasa de variación del empleo"
        tests:
          - not_null
      
      - name: cons_price_idx
        description: "Índice de precios al consumidor"
        tests:
          - not_null
      
      - name: cons_conf_idx
        description: "Índice de confianza del consumidor"
        tests:
          - not_null
      
      - name: euribor3m
        description: "Tasa Euribor a 3 meses"
        tests:
          - not_null
      
      - name: nr_employed
        description: "Número de empleados"
        tests:
          - not_null
      
      - name: y
        description: "¿El cliente suscribió un depósito a plazo?"
        tests:
          - not_null
          - accepted_values:
              values: ['no', 'yes']
