version: 2

sources:
  - name: raw
    description: "Raw data sources from BigQuery"
    database: dusa-prj-sandbox
    schema: raw
    tables:
      - name: bank_marketing
        description: "Main bank marketing dataset from UCI repository"
        columns:
          - name: age
            description: "Age of the customer"
            tests:
              - not_null
          - name: job
            description: "Type of job"
            tests:
              - not_null
          - name: marital
            description: "Marital status"
            tests:
              - not_null
          - name: education
            description: "Education level"
            tests:
              - not_null
          - name: default
            description: "Has credit in default"
          - name: balance
            description: "Average yearly balance in euros"
          - name: housing
            description: "Has housing loan"
          - name: loan
            description: "Has personal loan"
          - name: contact
            description: "Contact communication type"
            tests:
              - not_null
          - name: day
            description: "Last contact day of the month"
            tests:
              - not_null
          - name: month
            description: "Last contact month of year"
            tests:
              - not_null
          - name: duration
            description: "Last contact duration in seconds"
          - name: campaign
            description: "Number of contacts performed during this campaign"
          - name: pdays
            description: "Number of days since last contact from previous campaign"
          - name: previous
            description: "Number of contacts performed before this campaign"
          - name: poutcome
            description: "Outcome of the previous marketing campaign"
          - name: y
            description: "Has the client subscribed a term deposit"

      - name: bank_additional
        description: "Bank marketing dataset with additional socio-economic context"
        columns:
          - name: age
            description: "Age of the customer"
            tests:
              - not_null
          - name: job
            description: "Type of job"
            tests:
              - not_null
          - name: marital
            description: "Marital status"
            tests:
              - not_null
          - name: education
            description: "Education level"
            tests:
              - not_null
          - name: default
            description: "Has credit in default"
          - name: housing
            description: "Has housing loan"
          - name: loan
            description: "Has personal loan"
          - name: contact
            description: "Contact communication type"
            tests:
              - not_null
          - name: month
            description: "Last contact month of year"
            tests:
              - not_null
          - name: day_of_week
            description: "Last contact day of the week"
            tests:
              - not_null
          - name: duration
            description: "Last contact duration in seconds"
          - name: campaign
            description: "Number of contacts performed during this campaign"
          - name: pdays
            description: "Number of days since last contact from previous campaign"
          - name: previous
            description: "Number of contacts performed before this campaign"
          - name: poutcome
            description: "Outcome of the previous marketing campaign"
          - name: emp_var_rate
            description: "Employment variation rate - quarterly indicator"
          - name: cons_price_idx
            description: "Consumer price index - monthly indicator"
          - name: cons_conf_idx
            description: "Consumer confidence index - monthly indicator"
          - name: euribor3m
            description: "Euribor 3 month rate - daily indicator"
          - name: nr_employed
            description: "Number of employees - quarterly indicator"
          - name: y
            description: "Has the client subscribed a term deposit"
            tests:
              - not_null